version: 2.1

executors:
  default:
    docker:
      - image: circleci/python

jobs:
  orb-build-test:
    executor: default
    steps:
      - run: sudo bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"
      - checkout
      - run: circleci config pack orb | tee packed.yml
      - store_artifacts:
          path: packed.yml
          destination: orb
      - run: circleci orb validate packed.yml
      - run: circleci orb publish packed.yml fernfernfern/diag@dev:volatile --token ${CLI_TOKEN}
      - run: circleci config process > orb_test_config.yml
      - run: |
          curl --user ${CLI_TOKEN}: \
            --request POST \
            --form config=@orb_test_config.yml \
            --form notify=false \
              https://circleci.com/api/v1.1/project/github/fernfernfern/diag-orb/tree/master
workflows:
  daig-orb:
    jobs:
      - orb-build-test