version: 2.1

executors:
  default:
    docker:
      - image: circleci/python

jobs:
  orb-build:
    executor: default
    steps:
      - run: sudo bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"
      - checkout
      - run: circleci config pack orb | tee packed.yml
      - store_artifacts:
          path: packed.yml
          destination: orb
      - run: circleci orb validate packed.yml
      - run: circleci setup --token $CLI_TOKEN --host https://circleci.com
  orb-test:

workflows:
  daig-orb:
    jobs:
      - orb-build
      - orb-test:
          requires: orb-build