version: 2.1

executors:
  default:
    docker:
      - image: circleci/python

jobs:
  orb-build-test:
    executor: default
    steps:
      - run: sudo bash -c "$(curl -fSl https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh)"
      - checkout
      - run: circleci config pack orb | tee packed.yml
      - store_artifacts:
          path: packed.yml
          destination: orb
      - run: circleci orb validate packed.yml
      - run: circleci orb publish packed.yml fernfernfern/diag@dev:volatile --token ${CLI_TOKEN}
      - run: |
          curl -X POST --header "Content-Type: application/json"  -d '{"branch":"deploy"}' https://circleci.com/api/v1.1/project/github/fernfernfern/diag-orb/build?circle-token=${CLI_TOKEN}

workflows:
  daig-orb:
    jobs:
      - orb-build-test