version: 2.1

orbs:
  diag: fernfernfern/diag@dev:volatile

executors:
  default:
    docker:
      - image: circleci/python

jobs:
  build:
    executor: default
    steps:
      - run: sleep 10

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          pre-steps:
            - diag/create-sample-data
            - diag/record-top
          post-steps:
            - diag/post-steps
