version: 2.1

orbs:
  diag: fernfernfern/diag@dev:volatile

commands:
  simple:
    steps:
      - run: sleep 5

executors:
  docker:
    parameters:
      image:
        type: string
        default: python
      tag:
        type: string
        default: latest
    docker:
      - image: circleci/<< parameters.image >>:<< parameters.tag >>
  macos:
    macos:
      xcode: "10.1.0"
  machine:
    machine: true

jobs:
  docker:
    executor: docker
    steps:
      - diag/memory-fix
      - diag/post-steps
  macos:
    executor: macos
    steps:
      - run: | 
          mkdir -p ~/project/fastlane
          echo fastfile > ~/project/fastlane/Fastfile
          echo appfile > ~/project/fastlane/Appfile
          echo gymfile > ~/project/fastlane/Gymfile
          mkdir -p ~/project/ccidiag.xcodeproj
          echo project > ~/project/ccidiag.xcodeproj/project.pbxproj
      
      - diag/ios-logs
  machine:
    executor: machine
    steps:
      - diag/env-info
      - diag/memory
      - diag/sample-data
      - diag/simulate

workflows:
  my-workflow:
    jobs:
      - docker
      - macos
      - machine